version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build SharpenUp/SharpenUp.csproj
      - run:
          name: Test
          command: >-
            dotnet test SharpenUp.Tests/SharpenUp.Tests.csproj --logger
            "junit;LogFileName=xunit/results.xml"
      - store_test_results:
          path: SharpenUp.Tests/TestResults
      - run:
          name: Get Code Coverage
          command: >-
            dotnet test SharpenUp.Tests/SharpenUp.Tests.csproj
            /p:CollectCoverage=true /p:CoverletOutput=TestResults/
            /p:CoverletOutputFormat=opencover
      - run:
          name: Upload to Coveralls
          command: >-
            csmacnz.Coveralls --opencover -i
            SharpenUp.Tests/TestResults/coverage.opencover.xml
            --useRelativePaths
